--- #YAML:1.0
name:               Data-Lua
version:            0.02
abstract:           Parse variables out of Lua code.
author:
    - Michael Fowler <mfowler@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Inline::Lua:       0
    Test::NoWarnings:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
