# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Lua
version:      0.01
version_from: lib/Data/Lua.pm
installdirs:  site
requires:
    Inline::Lua:                   0
    Test::NoWarnings:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
